== Additional configuration to run the domibusConnectorClient-Application in iSupport mode

iSupport has a special setup to interact between the iSupport backend application and e-CODEX.
Messages are stored in a different way to the filesystem for the domibusConnectorClient (dCC) to pick up than the standard of the dCC foresees.
To cope with those specialities, a profile "iSupport" has been implemented with a certain filesystem handling.

=== Activating the iSupport profile

To let the dCC know that it must respect the iSupport specific filesystem handling, a standard spring property to enable profiles must be set with the iSupport value.
In the properties file it looks like this: 

[source,properties]
----

#activate to enable iSupport message structure
spring.profiles.active=iSupport

----

=== Setting iSupport specific message properties

An e-CODEX message requires some necessary ebms specific data to be able to be addressed properly.
Only a few of them are delivered within an iSupport message from the iSupport backend application.
Those that are required, but missing, need to be set with standard values in the properties of the domibusConnectorClient.

[source,properties]
----

connector-client.storage.filesystem.message-properties.fileName=header.xml
connector-client.storage.filesystem.message-properties.service=${service name from PModes}
connector-client.storage.filesystem.message-properties.serviceType=${service type from PModes}
connector-client.storage.filesystem.message-properties.action=${action name from PModes}
connector-client.storage.filesystem.message-properties.fromPartyRole=${initiator role name from PModes}
connector-client.storage.filesystem.message-properties.fromPartyIdType=${party id type value of party sending}
connector-client.storage.filesystem.message-properties.toPartyRole=${responder role name from PModes}
connector-client.storage.filesystem.message-properties.toPartyIdType=${party id type value of party receiving}

connector-client.storage.filesystem.message-properties.iSupportOutgoingDir=${directory name relative to connector-client.storage.filesystem.messages.path value}
connector-client.storage.filesystem.message-properties.iSupportIncomingDir=${directory name relative to connector-client.storage.filesystem.messages.path value}
connector-client.storage.filesystem.message-properties.processedFileName=.processed

----

All of those properties are instantiated with default values. If those standard values need to be different, then the corresponding property just needs to be set in the config properties file of the domibusConnectorClient.

The values mostly depend on values given by the p-Modes.

==== fileName
indicates how the file of iSupport messages is named where the domibusConnectorClient finds the StandardBusinessDocumentHeader.

==== service
Is the name of the ebms Service. Has to match the iSupport specific value from the PModes.

==== serviceType
Is the value of the ebms Service type. Has to match the iSupport specific value from the PModes.

==== action
Is the name of the ebms Action. Has to match the iSupport specific value from the PModes.

==== fromPartyRole
Is the value of the initiator role of the iSupport process. Has to match the iSupport specific value from the PModes.

==== fromPartyIdType
Is the value of the party ID type the sending party has. Has to match the iSupport specific value from the PModes.

==== toPartyRole
Is the value of the responder role of the iSupport process. Has to match the iSupport specific value from the PModes.

==== toPartyIdType
Is the value of the party ID type the receiving party has. Has to match the iSupport specific value from the PModes.

==== iSupportOutgoingDir
Is the directory relative to the path set with property connector-client.storage.filesystem.messages.path. In this drectory the domibusConnectorClient searches for new, not yet processed messages.

*Received ETSI-REM evidences are stored in the message folder of the originally processed message. If the directory is changed, the folder is not found and the evidence cannot be stored*

*For iSupport, the directory name of the message directory is transported to the receiving domibusConnectorClient*

==== iSupportIncomingDir
Is the directory relative to the path set with property connector-client.storage.filesystem.messages.path. In this drectory the domibusConnectorClient stores new messages on reception.

*For iSupport, the directory name of the original message directory on the senders side is transported to the receiving domibusConnectorClient. The new received message will be stored in a directory with the same name.*

==== processedFileName
Marks the name of the empty file generated by the domibusConnectorClient and stored in every message folder that has been processed. This file avoids that messages are processed again.

*Changing this property once messages have already been processed may cause those messages to be processed again!*
